version: '3.8'

services:
  nginx-server:
    build:
      dockerfile: docker/Dockerfile.nginx
      context: ..
    volumes:
      - ../data/container/nginx:/app:z
    cpus: '2'
    mem_reservation: 8192M
    ports: 
      - 8005:80


  apache-server:
    build:
      dockerfile: docker/Dockerfile.apache
      context: ..
    volumes:
      - ../data/container/apache:/app:z
    cpus: '2'
    mem_reservation: 8192M
    ports: 
      - 8006:80